spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: mh
    password: mh2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        provider:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: email

          registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri:

jwt:
  secret: MpxOCb91IgjzZ5UPIeuLQFtikcE83bRa
  expiration: 86400000
  refresh-expiration: 604800000


server:
  port: 8080

frontend:
  url: http://localhost:3000